# Server configurations
server:
 port: 8080
 ginMode: "release"
 verbose: false

database:
 uri: "mongodb://localhost:27017"
 db: "home"

station-rest-client:
 baseURL:        "http://"
 connectTimeout: 50
 timeout:       100
 disableCache:   true
 disableTimeout: false
