# Server configurations
server:
 port: 6980
 ginMode: "debug"

database:
 uri: "mongodb://192.168.1.100:27017"

station-rest-client:
 baseURL:        "http://"
 connectTimeout: 50
 timeout:       100
 disableCache:   true
 disableTimeout: false
