# Server configurations
server:
 port: 6980
 ginMode: "debug"
 verbose: true

database:
 uri: "mongodb://192.168.1.100:27017"
 db: "home"

station-rest-client:
 baseURL:        "http://"
 connectTimeout: 50
 timeout:       100
 disableCache:   true
 disableTimeout: false

slow-station-rest-client:
 baseURL:        "http://"
 connectTimeout: 100
 timeout:       200
 disableCache:   true
 disableTimeout: false
